name: Update arXiv Econ Papers Daily

on:
  # 允许手动触发，方便测试
  workflow_dispatch:
  # 定时触发：周一至周五的 03:00 UTC (即北京时间 11:00)
  schedule:
    - cron: '0 3 * * 1-5'

# 授予工作流写入仓库内容的权限
permissions:
  contents: write

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run update script for arXiv
        env:
          KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
        run: python update_arxiv.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update daily arXiv econ papers"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: README.md
